name: Build and Deploy to Azure

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.steveanik }}
          password: ${{ secrets.Mypassword@1228 }}

      - name: Build Docker image
        run: |
          docker build . -t your-docker-repo/your-image-name:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push your-docker-repo/your-image-name:${{ github.sha }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: AI-Chatbot-Server
          slot-name: production  # Change if you're using slots
          images: steveanik/langchain-ai-chatbot-server:latest${{ github.sha }}
