# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - AI-Chatbot-Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: steveanik
        password: dckr_pat_i1sFRuW77XsMsjIObgSNt5iE3Q4

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: steveanik/langchain-ai-chatbot-server:main
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ai-chatbot-server-bdejgpc5fjdpejaz.centralus-01.azurewebsites.net
    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'AI-Chatbot-Server'
        slot-name: 'production'
        publish-profile: AzureAppService_PublishProfile_eb9d08e74cc24d4cb8b09d88f66d6f3f
        images: 'index.docker.io/26fff7eb896e4dd48f711c1d3919513e/steveanik/langchain-ai-chatbot-server:main'
